### PR TITLE
Cooccurance table link fixed

### LINKED ISSUE #410: Individual id is not getting appended properly to the Co-occurrences table
**Expected Behavior**
1. Navigate to Individual Page
2. Scroll to co-occurrence table
3. click on individual name
4. get navigated to the new individuals

**Current Behavior**
1. Navigate to Individual Page
2. Scroll to co-occurrence table
3. click on individual name
4. page does not open correctly

_Technical Investigation_
Another existing issue was seen, in the Co-occurrences table on Individuals page, while applying fix for this issue. Individual id is not getting appended properly to the Co-occurrences table links, hence clicking on the table rows does not navigate to proper URLs.

Screen Shot 2024-03-14 at 6 14 48 PM

Screen Shot 2024-03-14 at 6 14 55 PM

This is happening because the individual display name is being used while forming the URL, the id (UUID) is to be used instead. If there is a ticket for this or if a ticket is created, I can create a PR with the fix.

_Originally posted by @NNattoji in _https://github.com/WildMeOrg/Wildbook/issues/365#issuecomment-1998727320_
_Additional context https://github.com/WildMeOrg/Wildbook/issues/271#issuecomment-2004531657_

### PR DESCRIPTION
**Pull request by NNattoji**
Individual UUID appended to display name in id variable. The UUID is then split later on, so that the 'Occurring With' column shows only the display name as before, while the UUID is used to set the 'class' attribute which is used to form the URL for the cooccurrence table link.

PR fixes #410 

**Changes**
- Edited Functions: getIndividualIDFromEncounterToString, getData and makeTable in encounter-calls.js

### CODE REVIEW

File: src/main/webapp/javascript/bubbleDiagram/encounter-calls.js [hunk 1]
```diff
@@ -45,14 +47,14 @@ var getData = function(individualID, displayName) {
 		
 				//var thisEncIndID = jsonData[i].encounters[j].individualID;   ///only when we fix thisOcc.encounters to be real json   :(
 				//console.info('i=%d, j=%d, -> %o', i, j, thisEncIndID);
-				if (!thisEncIndID || (thisEncIndID===displayName)) continue;  //unknown indiv -> false
-				if(encounterArray.includes(thisEncIndID)) {
-				} 
-				else {
-		    		encounterArray.push(thisEncIndID);
+				var individualName = thisEncIndID.split(" id=")[0];
```
Comment (naknomum) [inline src/main/webapp/javascript/bubbleDiagram/encounter-calls.js:50]: i think this might throw a js error if `thisEncIndID` is `false` ... so maybe we should have the `if (!thisEncIdId) continue;` block _before_ this.

**Review by naknomum — CHANGES_REQUESTED** [review]
one tiny change to catch what i think is a possible js error that could pop up

File: src/main/webapp/javascript/bubbleDiagram/encounter-calls.js (hunk 1 above)
Comment (NNattoji) [reply src/main/webapp/javascript/bubbleDiagram/encounter-calls.js:51]: The check has been moved above now.

**Review by naknomum — APPROVED** [review]
lgtm
