### PR TITLE
Issue 756 merge individual automation and notification fixes

### LINKED ISSUE #756: Merge request response saved in session but not in database
**Expected behavior**
When a user rejects a merge request, the merge is halted and the individuals in question remain unchanged. The notification disappears.

**Current behavior**
When a user rejects a merge request, the notification remains until it is dismissed and stays gone for the session. Once a new login session begins, the notification reappears with a prompt to accept or ignore.

This is a data integrity concern because the merge automatically occurs after 2 weeks. If the response isn't being saved to the database, the merge will complete despite multiple rejections.

**Testing notes**

1. First notification

2. Success message after Deny was clicked

3. New notification to Dismiss after clicking Deny

4. When a new login session starts, the notification pops up again. Two are displayed here due to testing the same merge twice.

**Community link**
https://community.wildme.org/t/recurring-incorrect-merge-notification/3335

### PR DESCRIPTION
**Pull request by holmbergius**
[Plain-text summary description of the solution. Include any class updates, new or edited functions, significant changes to UX, etc]

PR fixes #756 

**Before you Submit!**
* Is all the text internationalized?
* If you made a change to the header, did you update the react, jsp, and html?
* Are all depedencies at a locked version?
* Did you adhere to [best practices](https://wildbook.docs.wildme.org/contribute/code-guide.html)?
* Is there a quick [unit test](https://wildbook.docs.wildme.org/contribute/tests.html) you can add?

### CODE REVIEW

File: src/main/java/org/ecocean/StartupWildbook.java [hunk 1]
```diff
@@ -290,19 +290,18 @@ private static void startWildbookScheduledTaskThread(String context) {
...
-                    ArrayList<WildbookScheduledTask> scheduledTasks =
-                    myShepherd.getAllIncompleteWildbookScheduledTasks();
+                    ArrayList<WildbookScheduledTask> scheduledTasks = myShepherd.getAllIncompleteWildbookScheduledTasks();
                     for (WildbookScheduledTask scheduledTask : scheduledTasks) {
                         if (scheduledTask.isTaskEligibleForExecution()) {
                             scheduledTask.execute(myShepherd);
                         }
                     }
                 } catch (Exception e) {
-                    myShepherd.rollbackAndClose();
```
Comment (naknomum) [inline src/main/java/org/ecocean/StartupWildbook.java:302]: i am wondering if this `rollbackAndClose()` might cause something in the task execution to not be persisted, for example, there is a `myShepherd.throwAwayMarkedIndividual()` buried in `mergeIndividuals()` that i _think_ might be affected by this. will expand a little on this in slack....

Comment (holmbergius) [reply src/main/java/org/ecocean/StartupWildbook.java:302]: Hi @naknomum 

The WildbookScheduledTask.execute() method (and anything inheriting from it) is responsible for its own persistence with this Shepherd and for handling its exceptions in a way that allows other tasks to still execute. I think this method is doing the right thing by serving as an overall catch-all, but I did update ScheduledIndividualMerge to ensure it unwound its changes on exception.

**Review by naknomum — APPROVED** [review]
looks good
